### ISSUE TITLE
Mesamatrix does not parse the gl3.txt anymore

### ISSUE THREAD

**Issue by issueaccpost** [MightyCreak/mesamatrix#106]
dont know if you are aware

Last time GL3.txt was parsed: 2016-07-29 06:06:37 (GMT +0200)

**Comment by MightyCreak** [comment]
Don't worry, it's normal. GL3.txt is parsed only it has changed (i.e. a commit changed the file), that's why the date is pretty old, it's because there hasn't been a lot of changes lately.

Normally, there should be around 15 min between the time a commit is done and the parsed date, but this time it's different (commit: 22/07, parsed: 29/07) because I changed the code to have the [new extensions](https://mesamatrix.net/#Version_OtherExtensions) and so I needed to force a new complete parse (to also have the history of these extensions).

Thanks ;)
