### ISSUE TITLE
Discrepancies between OpenGL and OpenGL ES regarding GL_KHR_robustness

### ISSUE THREAD

**Issue by MatthewRaymond** [MightyCreak/mesamatrix#116]
GL_KHR_robustness under OpenGL 4.5 is shown as completed on 2016-10-05 for nvc0 and radeonsi, but it's missing for the same drivers and extension under OpenGL ES 3.2. For the i965 driver, the dates of completion are different: 2016-05-25 for OpenGL 4.5 versus 2016-05-26 for OpenGL ES 3.2. Am I missing something? Are there subtle differences between OpenGL and OpenGL ES for this extension that effectively makes this two extensions?

**Comment by MatthewRaymond** [comment]
This issue has largely gone away due to an update in Mesa's features.txt file. Looks like this issue is because the features.txt file has two separate listings, and each one is loaded independently into MesaMatrix. It's difficult to say if this is actually a bug in MesaMatrix, or if this is a bug in the features.txt that has been corrected. I guess I can consider this closed for now, however, because I must concede the possibility that an extension could work for OpenGL but not OpenGL ES and vice versa.

**Comment by MightyCreak** [comment]
Hi!

Even though the two extensions have the same name, mesamatrix considers them differently because they aren't in the same "namespace". One is in GL the other in GLES.

The only link I do between two extensions is when there is an explicit text for it, like that: `all drivers that support GL_ARB_draw_buffers_blend` ([line 261](https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt#n261)).

That might explain why there was a problem before. But it's still possible that there's a bug as well 😉
