### ISSUE TITLE
Feature: Mark some unsupported features as unsupported by hardware

### ISSUE THREAD

**Issue by RobinMcCorkell** [MightyCreak/mesamatrix#12]
As posted by [schmidtbag on the Phoronix forums](http://www.phoronix.com/forums/showthread.php?106487-Mesa-Gets-Closer-To-Having-OpenGL-4-0-Tessellation-Support&p=441286#post441286), the colour used for unsupported features should be different depending on hardware support. What about a clear/near-transparent colour for such non-features?

**Comment by MightyCreak** [comment]
For more information, see the email in the ML: http://lists.freedesktop.org/archives/mesa-dev/2015-July/090054.html

**Comment by MightyCreak** [comment]
Based on https://secure.freedesktop.org/~imirkin/glxinfo/glxinfo.js (see `UNSUPPORTED` object).

List of unsupported extensions (WIP):
* R600
  * GL_ARB_gpu_shader5
  * GL_ARB_tessellation_shader

**Comment by dro123** [comment]
This is the real _hardware_ R600 not the driver r600! 

The driver will support both gpu_shager5 and tessellation because there's hardware which are driven by this driver that support these. Just the oldest hardware supported by the driver (the hardware that gave the driver the name) can't support these.

**Comment by MightyCreak** [comment]
Yep... I've just had a talk with the devs and it seems more and more impossible to flag some mesamatrix drivers extensions as unsupported since 'r600' (for instance) is not one driver but a group of drivers supporting a group of different hardwares.

I'll try to find extensions that are unsupported for all the drivers in the same driver category. Might not be a lot of them....

**Comment by dro123** [comment]
Like I said before: "This is a little bit more difficult than it seems to be." ;-)

It's actually _one_ driver not a group of drivers. But one driver can support more than one piece of hardware. And what makes it difficult is that depending on the hardware the driver is running on, it will report different capabilities.

The thing you see in GL3.txt just says that for this driver there exists at least one piece of hardware where this feature will be reported and is working.

**Comment by MightyCreak** [comment]
Thx, it's a bit clearer! ;)

But what is the difference between r600 and r600g then?

**Comment by dro123** [comment]
Nowadays? No difference :-)

You have to go back in time a little bit to understand this.

Traditionally in mesa there was no gallium middle layer. Gallium is a layer in the mesa driver that is doing a lot of work that was originally done inside every driver with a driver specific implementation.

When gallium was introduced there were two drivers for R600,R700, EG, ... hardware:
1) The classic r600 driver not using gallium and implementing a lot of stuff in the driver but was proven working and was tested more thoroughly
2) The r600 gallium driver (short r600g) that used the gallium infrastructure but was new, had more bugs and was more or less untested

You had to decide during build time which driver you wanted to use (either-or), because the libraries had the same name: dir/r600_dri.so. By default you would get the classic version.

At some point in time the gallium driver (r600g) became the default driver for R600,R700, EG, ... hardware and the classic driver not using gallium was removed. 

So nowadays people just call the r600 gallium driver 'r600' because there's no other.

**Comment by MightyCreak** [comment]
Thanks a lot for all these explanations. It's quite crystal clear now :)

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
