### ISSUE TITLE
Some AMD GPUs don't work in the decoder ring

### ISSUE THREAD

**Issue by SuicSoft** [MightyCreak/mesamatrix#123]
Some AMD GPUs like RX 480 and R5 M430 dont work in the decoder ring

**Comment by SethBarberee** [comment]
From glancing at the code, it seems like this line would need to be changed for the Polaris cards:
https://github.com/MightyCreak/mesamatrix/blob/4e7c69373c632ad5bca97c84c7392f03fb23cf55/http/js/drivers.js#L212

**Comment by MightyCreak** [comment]
Retrospectively, I think it would be better to do a hardcoded list of all the AMD GPUs. There might be a few dozen of them, but since they don't change over time, it would be quite easy (and easier) to maintain.

If you're willing to make a list (even just a start would already be helpful). Something like an array of pairs `[ gpu, family ]` (e.g. `[ 'R9 285', 'Volcanic Islands' ]`).

**Comment by SethBarberee** [comment]
So would you prefer a .txt file or how so? I can easily get started...

**Comment by MightyCreak** [comment]
A text file is ok, thank you! ;)

**Comment by MightyCreak** [comment]
This is issue is too old. Closing it.
