### ISSUE TITLE
Add vivante GPU

### ISSUE THREAD

**Issue by mmaret** [MightyCreak/mesamatrix#129]
Hi,

The etnavive driver just hit OpenGL 2.1. 
It could be nice to have it's support information here too :)

Thanks,

Mathieu

**Comment by MightyCreak** [comment]
Hello!

I'd be glad to, but the data need to be in the Mesa repo first (here: https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt)

Since it is only OpenGL 2 and that this file only tracks versions from 3, I am skeptical that the Mesa devs will add vivante for now.

But you can ask on their mesa-users mailing list. They'll know users would like to have this information 😉

**Comment by mmaret** [comment]
Thanks for the informations !

OpenGL 2.0 get supported only few days before OpenGL2.1 so, in any ways, it would require too much time before OpenGL 3 get supported :)

**Comment by mmaret** [comment]
Fixed :)
