### ISSUE TITLE
Only OpenGL ES ≥3.1 is parsed

### ISSUE THREAD

**Issue by mirh** [MightyCreak/mesamatrix#130]
I mean, I'm talking about the table in the top right corner of the website

**Comment by MightyCreak** [comment]
I don't understand, I see OpenGL ES 3.2 for mesa and i965.

**Comment by mirh** [comment]
Better this way? 🙃

**Comment by MightyCreak** [comment]
"N/A" means "Not Available", which is exactly the case here because there is no data available in [features.txt](https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt). Either the drivers can do GLES ≤3.0, or they can't, I have no way to know that with the data I'm parsing.

So it's not really up to me, but you can ask the mesa devs for that 😄 
If they do it, I'll make sure it's tracked down here, promise!
But until then, I'll close this issue.

Cheers!

**Comment by mirh** [comment]
So.. I don't want to be a killjoy or something, but you know there is `GL_ARB_ES2_compatibility` ?

**Comment by MightyCreak** [comment]
Interesting, I could look at that. That being said, it also means that the drivers not only have to implement this extension, but they also have to be compatible with OpenGL 4.1. And right now, even if all the drivers have implemented this extension, none of those that are N/A are also compatible with OpenGL 4.1.

I know that a program can ask if an extension of a later version does exist, but in most of the case, the games, for instance, don't care doing that. They just take official version supported by the driver and if it's enough, they go on.

So when the other drivers -- namely softpipe, llvmpipe, swr, nv50 and freedreno -- will get to OpenGL 4.1, I'll implement a way to check the dependency on this extension, but hopefully, until they get there, they would already have implemented all the extensions for GL ES 3.1.

That's why, for now (and I'm not against changing my position in the future), I would prefer to focus on Vulkan support instead.

**Comment by mirh** [comment]
Mhh?
I'm not sure what Vulkan has to do with this. 

Anyway, the point should be that if an extension is supported before his entire "feature set" you write it there - and GL just happens to be flagged by that, not other stuff. 
Especially considering it is a subset of GL, it makes no sense to make it correspond to the entire thing.

**Comment by stefano2734** [comment]
In Mesa3d.org there are some informations for some drivers for OpenGL less 3.0 and OpenGL ES less than 3.1.
Example
https://docs.mesa3d.org/drivers/lima.html

so it is only little Action of mesa developers necessary.

**Comment by mirh** [comment]
Those docs aren't really "law".

**Comment by stefano2734** [comment]
Other example with much information in detail: 
https://docs.mesa3d.org/drivers/panfrost.html

Zink starts with OpenGL 2.1
https://docs.mesa3d.org/drivers/zink.html
so some tests are done

no want, no way.
