### ISSUE TITLE
VK_KHR_device_group is shown as done for radv and not started for Mesa?

### ISSUE THREAD

**Issue by shmerl** [MightyCreak/mesamatrix#144]
It's reported as not started in [features.txt](https://cgit.freedesktop.org/mesa/mesa/tree/docs/features.txt).

**Comment by MightyCreak** [comment]
Yup, it's a fuck since the unofficial extensions became official with Vulkan 1.1. This will be fixed with the big refactoring I'm planning to do (right now the commits parser do way to much work for nothing and it leads to this kind of error in the end).

**Comment by bstaletic** [comment]
The same section of the features.txt also says `Vulkan 1.1 -- all DONE: anv, radv`.

**Comment by MightyCreak** [comment]
Well seen! It would need a Mesa dev actually to fix that. It's weird that an extension is not started and done at the same time.

**Comment by MightyCreak** [comment]
> Offtopic: There's a new commit adding something to thte features.txt that I don't even know how to read and I think mesamatrix isn't parsing that.

Yep, I've seen that. It would need yet another parsing exception to make it work 😞
Would have been nice if the mesa devs would consider mesamatrix parsing before adding stuff like that (especially since the mesamatrix.net is given at the end of the text file).

I think one day I'll propose a more standard way of writing this file, so that the parser is not a bunch of exception cases 😉

**Comment by bstaletic** [comment]
> (especially since the mesamatrix.net is given at the end of the text file)

Considering that, I think asking nicely about the format could go well.

**Comment by jmayer** [comment]
Looks OK nowadays. Maybe it's time to close this issue?

**Comment by MightyCreak** [comment]
It's seems fixed now. Maybe because the culprit commit is more than a year old now and I had to clone the repo again for the new Vulkan API.
