### ISSUE TITLE
OpenCL - software, emulation (D3D, virtualization, Vulkan)

### ISSUE THREAD

**Issue by Torinde** [MightyCreak/mesamatrix#232]
In the OpenCL tables are missing columns showing what's supported in [D3D](https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-CLOn12-Mesa-SPIR-V), in virtualization (like virgl/vn), in Vulkan?, via software

![image](https://user-images.githubusercontent.com/97228894/159167212-6d523e3c-ba72-419e-8f2b-17f50adb3839.png)
![image](https://user-images.githubusercontent.com/97228894/159167293-ed454432-c834-4130-9043-9ba2c6d8f94d.png)

**Comment by MightyCreak** [comment]
Hi!

It's not a bug, this happens because the D3D driver is not listed in the features.txt file (see the [OpenCL section](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt#L604)).

If the Mesa devs add the driver here, I'll be able to track it, but until then Mesamatrix can only follow what features.txt says, sorry
