### ISSUE TITLE
OpenGL 2.x, OpenGL ES 2.x and 3.0 not in Tables

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#233]
Some driver can do OpenGL 2, OpenGL ES 2 and 3.0, but there are not in tables.

In  summary there are N/A, but there is more.

**Comment by MightyCreak** [comment]
Thanks for reaching out.

I am limited to the content of Mesa's [features.txt](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt) file and as you can see it doesn't document the support before OpenGL 3.0 and OpenGL ES 3.1.

I'll close this issue because I can't really do anything about that, it is up to the Mesa devs to document that or not. But from what I gathered, they don't want to bother with these old APIs versions ([OpenGL ES 3.0](https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_3.0) was released in 2012, while [OpenGL 2.0](https://en.wikipedia.org/wiki/OpenGL#OpenGL_2.0) was release in 2004).
