### ISSUE TITLE
Expose GL_KHR_shader_subgroup in "Extensions that are not part of any OpenGL or OpenGL ES version"?

### ISSUE THREAD

**Issue by oscarbg** [MightyCreak/mesamatrix#252]
Hi,

this is an interesting extension (or group of extensions), and a KHR ext, that sadly isn't supported by Mesa right now..

I have opened an issue requestion for support (radeonsi,iris,zink at least):
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6545

would be nice if people can check from your site also Mesa status on this extension..

seems the place for it is in:"Extensions that are not part of any OpenGL or OpenGL ES version"

note different implementations show the basic one (GL_KHR_shader_subgroup) or list all variants as supported extensions..

for example Nvidia only shows basic one:
http://opengl.gpuinfo.org/displayreport.php?id=7855
GL_KHR_shader_subgroup

while Intel Windows driver shows all:
http://opengl.gpuinfo.org/displayreport.php?id=7834

GL_KHR_shader_subgroup
GL_KHR_shader_subgroup_arithmetic
GL_KHR_shader_subgroup_ballot
GL_KHR_shader_subgroup_basic
GL_KHR_shader_subgroup_clustered
GL_KHR_shader_subgroup_quad
GL_KHR_shader_subgroup_shuffle
GL_KHR_shader_subgroup_shuffle_relative
GL_KHR_shader_subgroup_vote

leave up to you if you want to expose, and if yes if as one ext or multiple ones..

thanks..

**Comment by MightyCreak** [comment]
Thanks for contributing to both Mesamatrix and mesa!

You did the right thing by opening an issue directly on mesa's repository. I can't do much here as Mesamatrix merely reads features.txt. Once the extension(s) will be exposed there, the Mesamatrix service will automatically list them.

So since we can't do much more (in this repo) than patiently wait for the mesa devs, I'll close this issue here.
