### ISSUE TITLE
RustiCL progress?

### ISSUE THREAD

**Issue by romulasry** [MightyCreak/mesamatrix#268]
https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1386610-mesa-23-1-released-with-radeonsi-rusticl-opencl-radv-gpl?p=1386635#post1386635

"Is mesamatrix.net going to be updated to track RustiCL progress? "

**Comment by MightyCreak** [comment]
I can't do much about that as [features.txt](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt) doesn't track it.

I'll close this issue, but if features.txt is updated with newer OpenCL drivers, feel free to reopen it.

**Comment by norablackcat** [comment]
Hey there! I've been working on Rusticl and can add the supported tables but I was wondering If the site could possibly display both the clover details and the rusticl ones. Because their implementations are different and they support different extensions. 

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23051 related merge req

**Comment by MightyCreak** [comment]
I guess this issue is superseded by #269 ?
