### ISSUE TITLE
Nv50 and OpenGL ES 3.1 for some Hardware since Mesa 21.2

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#295]
actual state-of nv50  is here N/A.

See message 

https://www.phoronix.com/news/Nouveau-GLES-3.1-GT21x

**Comment by MightyCreak** [comment]
The results shown in Mesamatrix is synced with the latest commit of `features.txt`.

`GL 3.3, GLSL 3.30` is `all DONE` for `nv50`, but not for the next GL 4.0. As for GLES, the file says it isn't ready for `GLES3.1` (the very first version listed). Not that this is true IRL, but Mesamatrix strictly follows what's written in `features.txt`.

This will get automatically resolved when/if Ilia updates the file `features.txt`, that's why I'll close this issue :wink:
