### ISSUE TITLE
V3d compliant to OpenGL 2.1 since 2019

### ISSUE THREAD

**Issue by stefano2734** [MightyCreak/mesamatrix#298]
See 
https://www.raspberrypi.com/news/vc4-and-v3d-opengl-drivers-for-raspberry-pi-an-update/

in an additional comment in table summary is here more possible than n/a.

**Comment by stefano2734** [comment]
With openGL 3.1+ support in Mesa 23.3 the issue is solved for v3d.

**Comment by stefano2734** [comment]
Is done with openGL 3.1 in Mesa 23.3.

**Comment by stefano2734** [comment]
Done

**Comment by MightyCreak** [comment]
> in an additional comment in table summary is here more possible than n/a.

It's pretty difficult as the only source of information I have is the features.txt file (there are apparently others somewhere, but I don't know exactly where, and if they are machine readable).

For all the drivers with N/A, we don't really know what's their actual level of conformance. Even if we know v3D is conforming with OpenGL 2.1, hardcoding that will force me to parse various news media to keep being up to date with its state (and probably the state of the other N/A drivers, because this is a pandora box :wink: ).

**Comment by stefano2734** [comment]
V3d in mesamatrix is openGL 3.1+ since 2023.
So issue is done and can be closed.
