### ISSUE TITLE
Got errors while running `./mesamatrixctl -vvv setup`

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#30]
#### Steps to reproduce:
Simply run the command `./mesamatrix -vvv setup`

#### Result:
Command output:
```sh
~$ LANG=C ./mesamatrixctl -vvv setup
  RUN  'git' 'clone' '--bare' '--depth' '6000' 'git://anongit.freedesktop.org/mesa/mesa' '/home/mesamatrix/mesa.git'
  ERR  Cloning into bare repository '/home/mesamatrix/mesa.git'...
  ERR  
  RES  Command ran successfully
```
Problems:
- Not all the log (missing the git messages)
- Weird error lines

#### Expected result:
Display all the log lines and without errors.

**Comment by Xenopathic** [comment]
All output is being shown from `git` - the problem is that since `git` is running inside the new stdout interfaces from Symfony Console, it doesn't detect that it is connected to a terminal, so it doesn't display progress information (which requires terminal codes to erase text). It is possible to force it by using `--verbose` on the `git` command line, but I don't know what it will look like through PHP.

When you say 'weird error lines' you are referring to the `ERR` at the beginning of each git output line, correct? In that case, that's expected - git outputs progress information to standard error (stderr), which Symfony Console marks with `ERR`.

To be honest, we shouldn't really be calling external utilities from PHP anyway, we should be using [php-git](https://github.com/libgit2/php-git), but it isn't packaged for many distros at the moment so it wouldn't be a good idea to switch.

**Comment by MightyCreak** [comment]
I didn't know git was outputting on the error stream. I agree with you that php-git will be better.

Isn't there a switch in git that doesn't use specific terminal feature?

But if it's not possible, it's OK, we can live with it I suppose ;)

**Comment by MightyCreak** [comment]
We'll live with it for now ;)
