### ISSUE TITLE
http://mesamatrix.net/ down?

### ISSUE THREAD

**Issue by afritsch** [MightyCreak/mesamatrix#36]
I only get a nginx greeting, did something happen to the server?

Idea: I might access the site via ipv6, maybe something there is broken?

**Comment by MightyCreak** [comment]
It works well here for both mesamatrix.net and www.mesamatrix.net.

I did change a setting about IPv6 a while ago though...
Do you know how can I test an nginx server using IPv6? (using curl or something else...)

**Comment by Xenopathic** [comment]
@MightyCreak You might be able to use the free Teredo tunnelling service at http://www.trex.fi/service/teredo.html

**Comment by afritsch** [comment]
Every time I visit the site I only get this:
![mesamatrix](https://cloud.githubusercontent.com/assets/497652/6319252/50559a96-bab5-11e4-9317-86542d6eabbb.PNG)

I also have a VPS running nginx with ipv6 working. I used these sites to validate:
http://ip6.nl/
https://www.mythic-beasts.com/ipv6/health-check
http://validador.ipv6.br/

**Comment by MightyCreak** [comment]
IPv6 seems to be the problem indeed. I'll try to see how to fix that without breaking my other websites on my server.

**Comment by MightyCreak** [comment]
Nginx was listening to port 80 on IPv6, but only for the default server, that's why you had this greeting page. I changed my nginx mesamatrix server settings to this:

```nginx
    listen   80; ## listen for ipv4; this line is default and implied
    listen   [::]:80; ## listen for ipv6
```

Hopefully this will work, but I can't test since I don't have an IPv6 address. The only preview I have is this one: http://validador.ipv6.br/index.php?site=mesamatrix.net&lang=en and apparently it doesn't work, but maybe it's their cache system... I don't know...

**Comment by afritsch** [comment]
It's working now, thanks :-) Just had to ctrl+f5 (browser cache).

**Comment by MightyCreak** [comment]
:+1: 

I wish I had an IPv6 address, it would have been easier for me to test this kind of problem ;)
