### ISSUE TITLE
"commitparser_depth" config option doesn't work

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/mesamatrix#42]
I set it to 1 but it still does the whole history.

**Comment by MightyCreak** [comment]
Oh, I just saw that this is purely for the main display.

@Xenopathic do you think we could bind this config parameter with the actual parser?

**Comment by Xenopathic** [comment]
@MightyCreak The `commitparser_depth` config variable only affects CommitParser, not the parser of GL3.txt. I'd suggest introducing a new variable, `oglparser_depth`, to do what you want, since it is likely that an admin will want to show many revisions in the matrix (via modified dates) but only have 10 or so most recent commits listed.

**Comment by MightyCreak** [comment]
Flagged enhancement instead of bug, since it *would* be nice to have that, but right now it's doing what it's intended to do.
