### ISSUE TITLE
Vulkan support?

### ISSUE THREAD

**Issue by Nimroot** [MightyCreak/mesamatrix#94]
Not sure if it's going to be added to GL3.txt however I strongly believe that as Vulkan is actually the next big thing its support in mesa should somehow be fetched and listed for mesamatrix.

**Comment by MightyCreak** [comment]
Yep, I was looking at the git tree recently, but I haven't seen a file for that.

But I agree, as soon as I find a way to display the advancement of the open source drivers on Vulkan, I'll do it!

**Comment by arpu** [comment]
https://cgit.freedesktop.org/mesa/mesa/commit/?id=d5b4638d6a7f623f1ad937a840d68922f00e29cf

**Comment by MightyCreak** [comment]
Yep I've seen that, but it's only a todo list, it doesn't list the features that's been done. And also it is only for Intel.

**Comment by iamgreaser** [comment]
It would be a nuisance but you could check whatever is responsible for VkPhysicalDeviceFeatures.

`src/intel/vulkan/anv_device.c`, function `anv_GetPhysicalDeviceFeatures` seems to have an almost parseable list.

**Comment by MayeulC** [comment]
I saw on phoronix that VK_KHR_incremental_present [was enabled today][1] . 

When looking at the commit, the file [radv_entrypoints_gen.py][2] (and its anv counterpart) seems to keep track of the extensions. Following [this page on khronos' website][3], it looks like these extensions are stored in an xml file [there][4] (different versions exist in different branches). I am not sure how to differentiate "core" and "optionnal" ones, though.

What do you think about this? It looks like it might be interesting to keep track of the features, now that we have more capable drivers.

Another option is, of course, to create an equivalent to GL3.txt for Vulkan.

[1]: https://cgit.freedesktop.org/mesa/mesa/log/?qt=grep&q=VK_KHR_incremental_present
[2]: https://cgit.freedesktop.org/mesa/mesa/tree/src/amd/vulkan/radv_entrypoints_gen.py
[3]: https://www.khronos.org/registry/vulkan/
[4]: https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml

**Comment by MightyCreak** [comment]
@MayeulC if it is possible to extract the supported extensions directly from the mesa code, that would be the best solution.

I asked the ML for more information on that but didn't got much support. At least they're not against the principle.

I started to make a parser for the XML you mentioned. But I still don't know what exactly I should extract from it.

If you have more information I'll be glad to help you or code it myself.

**Comment by LinuxDonald** [comment]
https://cgit.freedesktop.org/mesa/mesa/commit/?id=fe3d2559d941f8f69dbdb369221af69a9974d017

**Comment by MightyCreak** [comment]
Yep! Seen this, I'll get on that as soon as I can, but I've got a lot of to do at my job. Should be better in 2 weeks.

**Comment by MightyCreak** [comment]
In the meantime, I'd need your opinion from you all: I'm wondering whether I should show the Vulkan data in a separate page (so we would have OpenGL and Vulkan in the menu), or if I should put everything in the same page.

I'm leaning toward the first solution since the OpenGL page is already pretty big.

**Comment by prcastro** [comment]
I wouldn't mind having Vulkan in a separate page.

**Comment by TotalCaesar659** [comment]
I guess, it should be better to have all in one page, both OpenGL and Vulkan.

**Comment by ebkalderon** [comment]
Perhaps you could have a single page with two tabs, one for each API?

**Comment by Evisceration** [comment]
I would make a single page with tabs as well.

Two pages does not seem to be as intuitive to use as the tabs approach.

**Comment by MightyCreak** [comment]
When I was talking about two pages, I was thinking to add one item in the top menu here:

![capture d ecran de 2017-08-04 08-41-48](https://user-images.githubusercontent.com/6382548/28969061-f355d8e0-78f0-11e7-9eb5-2eb4f9a780ca.png)

Instead of "Home" (which I never liked), I'd have "OpenGL" and then right next to it there would be "Vulkan". It seems to me to be like tabs, but maybe you've got another idea.

One thing for sure, I'd prefer not to add tabs under the menu. It seems overly complicated for a website that don't have that many data to show (let's be honest, it's not the next Amazon :D ).

**Comment by Evisceration** [comment]
> it's not the next Amazon :D

But it could be :)

Was thinking about loading it via JS, but may be overcomplicating the whole thing.

Two different pages makes sense as well, easy enough and gets the job done!

**Comment by MightyCreak** [comment]
What I like about two pages is that you can directly link to the Vulkan page, which will be more and more the most important page.

**Comment by bstaletic** [comment]
One more thing to note, there are users who disable javascript, or use a text based browser. So far mesamatrix has worked perfectly for those. Thus I'm in favor of two distinct pages and in turn keeping the users.

**Comment by sehraf** [comment]
Any update on this?

**Comment by MightyCreak** [comment]
I haven't worked on it a lot lately, but I have something in progress that reads the Vulkan data in features.txt. Now it's a story of showing it. I thought about making 2 pages, one for OpenGL and one for Vulkan, but I think the users expect to see everything in one page. Maybe later I'll simply do a smater page (possibility to show/hide APIs and drivers)

**Comment by Faalagorn** [comment]
If you have something brewing @MightyCreak, how about putting it somewhere, probably without even a link on the main page (or with a big **beta** sign on it, even if it's not 100% ready to have some comments about presentation? That way some feedback would help you deciding how to show the things on page better IMO :).

**Comment by MightyCreak** [comment]
Indeed, I could do a beta.mesamatrix.com. Right now I have a `vulkan_parser` branch, but I still have a lot of local code (that I don't push because it's not working yet).

That being said, not much is happening in the features.txt file right now. And the Vulkan 1.0 section doesn't list the extensions, just the drivers. So not a lot to display for now but the drivers supporting Vulkan.
