### ISSUE TITLE
Dependencies may not be correctly parsed

### ISSUE THREAD

**Issue by vhda** [MightyCreak/mesamatrix#95]
The following line marks all drivers as done, even when they don't implement GL_ARB_shader_image_load_store.

GL_OES_shader_image_atomic DONE (all drivers that support GL_ARB_shader_image_load_store)

**Comment by MightyCreak** [comment]
Yep... the parser doesn't do dependencies between extensions. It's a new feature of GL3.txt the mesa devs added.

Since I want the website to be as autonomous as possible, it's not going to be easy to solve this problem since each developer will write the sentence he/she prefers (basically we're talking about parsing natural language here, something that even Google struggles to do :D).

I'm strongly thinking about proposing a patch to formalize this file into something more computer-friendly.

**Comment by vhda** [comment]
Did not look at the code, but is it very hard to search for `/all drivers\s.*\s\(\w\+\)/` and then check if `$1` is a known feature? (Regular expression will need to be adapted to the language you are using :))

**Comment by MightyCreak** [comment]
It's completely possible to do that (and that would be my first try actually). What is worrying me is that one dev can write "all drivers that support ext xxx" and another one "done if ext xxx is too" or "works if ext xxx is done"

So many different way of writing it that may, in the end, conflict with other special sentences. For instance here if the whole line is green is because there is "all drivers" in the sentence. But the line will probably be green too if the dev wrote "not done for *all drivers* yet". You see my point?

But, I'm not closing this issue. I'm just pointing out the consequences of getting into this kind of parsing ;)

**Comment by vhda** [comment]
I completely understand :)
Thanks for your time answering this issue.

**Comment by Tele42** [comment]
This does not have to be perfect since mesa devs are clearly interested in collaborating, I recommend adding one clearly concise pattern for dependencies, then add a footnote to GL3.txt with the various parsing/format restrictions of GL3.txt for mesamatrix. There's no particular hurry right now as there's no feature sets reported as supported as a side effect of this, but it potentially will be in the future.

**Comment by MightyCreak** [comment]
Yep I did some commits recently to normalize a little bit GL3.txt and see how the Mesa devs will accept it. It was just a first pass, but I think I can start doing something from there.

They indeed seem to be collaborating, so I'll continue in this direction ;)

**Comment by FLHerne** [comment]
More fun with parsing; GL_OES_copy_image is in GL3.txt as "DONE (core only)"

If I understand the [thread](https://lists.freedesktop.org/archives/mesa-dev/2016-February/107774.html), this works for core Mesa only, not any drivers yet.

The matrix has it displayed as done for all drivers.

**Comment by MightyCreak** [comment]
That's weird because we have a syntax for that, it's `DONE ()` and it's already used plenty of times.

I'll discuss with Illia about that.

**Comment by FLHerne** [comment]
This (the original issue, not the glitch I commented about) doesn't seem fixed.

For example GL_OES_gpu_shader5 is ```DONE (all drivers that support GL_ARB_gpu_shader5)```, but is shown as done for all drivers when only i965 has implemented the ARB version.

**Comment by MightyCreak** [comment]
True, that fix would need much more work :(

**Comment by Mystro256** [comment]
Well the language seems to be consistent:

"all drivers that support GL_*"

It could be matched using something like regex, then it just grabs whatever the status is from the extension referenced for each driver. It would require whatever the equivalent to a lookup table is in PHP or some sort of recursive search... Note that I am not experienced with PHP, so I can't really comment too much on the specific implementation.

**Comment by sandain** [comment]
I'm not familiar with your code, but if I were to write something to solve this issue, this is what I would do:

1) During the parsing phase, add each completed extension/GLSL feature level found to a hash table for each driver.
2) Also during the parsing phase, look for dependencies and add them to dependency list for the extension (most extensions will have an empty list).  Here is a regex that looks for the dependencies: `/\(all drivers that support (.*)\+?\)/`.  Here is a hand made list of values this regex should catch:

* GLSL
* GLSL 1.30
* GLSL 1.30+
* GLSL 3.30
* GLSL 4.10
* GL_ARB_texture_multisample
* GL_ARB_draw_buffers_blend
* GL_ARB_gpu_shader5
* GL_ARB_shader_image_load_store
* GL_ARB_tessellation_shader
* GL_ARB_texture_stencil8
* GL_ARB_texture_multisample

3) During the presentation phase, when deciding what color to highlight a box, check the list of dependencies for each extension against the completed extensions hash table for the driver.

The only special case issue that I see is how to handle the unversioned GLSL dependency.  Maybe just assume that `"GLSL" == "GLSL 1.30"` since no lower GLSL levels are tracked in the `features.txt` file. The `+` in the `GLSL 1.30+` dependency is ignored by my regex above, so that shouldn't cause an issue.

**Comment by MightyCreak** [comment]
Done, but I can't parse GLSL since it seems there is no way to extract this information from features.txt.

**Comment by Tele42** [comment]
For now we can infer if a driver supports a GL version, it also supports the corresponding GLSL version

GL 3.0-3.2 = GLSL 1.30-1.50 and GLSL 3.30+ is obvious.

**Comment by MightyCreak** [comment]
Let's open another issue, shall we? I'm glad I was able to fix this one ;)
